# To test karpenter 
apiVersion: v1
kind: Namespace
metadata:
  name: karpenter-test
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: inflate
  namespace: karpenter-test
spec:
  replicas: 5
  selector:
    matchLabels:
      app: inflate
  template:
    metadata:
      labels:
        app: inflate
    spec:
      nodeSelector:
        karpenter.sh/capacity-type: on-demand
      containers:
      - name: inflate
        image: public.ecr.aws/eks-distro/kubernetes/pause:3.9
        resources:
          requests:
            cpu: 1
            memory: 1Gi
          limits:
            cpu: 1
            memory: 1Gi 