# Outputs for the EKS Terraform configuration

output "vpc_id" {
  description = "The ID of the VPC"
  value       = var.vpc_id
}

output "private_subnets" {
  description = "List of IDs of private subnets"
  value       = var.private_subnet_ids
}

output "public_subnets" {
  description = "List of IDs of public subnets"
  value       = var.public_subnet_ids
}

output "cluster_id" {
  description = "EKS cluster ID"
  value       = module.eks.cluster_id
}

output "cluster_endpoint" {
  description = "Endpoint for EKS control plane"
  value       = module.eks.cluster_endpoint
}

output "cluster_security_group_id" {
  description = "Security group ID attached to the EKS cluster"
  value       = module.eks.cluster_security_group_id
}

output "node_security_group_id" {
  description = "Security group ID attached to the EKS cluster"
  value       = module.eks.node_security_group_id
  
}

output "cluster_iam_role_name" {
  description = "IAM role name associated with EKS cluster"
  value       = module.eks.cluster_iam_role_name
}

output "cluster_certificate_authority_data" {
  description = "Base64 encoded certificate data required to communicate with the cluster"
  value       = module.eks.cluster_certificate_authority_data
  sensitive   = true
}

output "kubectl_config" {
  description = "kubectl config as generated by the aws eks get-token module"
  value       = module.eks.kubectl_config
  sensitive   = true
}

output "config_map_aws_auth" {
  description = "A kubernetes configuration to authenticate to this EKS cluster"
  value       = module.eks.config_map_aws_auth
}

output "node_groups" {
  description = "Outputs from EKS node groups"
  value       = module.eks.node_groups
}

output "cluster_name_with_suffix" {
  description = "EKS cluster name with random suffix"
  value       = local.cluster_name_with_suffix
}

output "karpenter_enabled" {
  description = "Whether Karpenter is enabled"
  value       = var.enable_karpenter
}

output "karpenter_node_role_arn" {
  description = "Karpenter node role ARN (if enabled)"
  value       = var.enable_karpenter ? "arn:aws:iam::${data.aws_caller_identity.current.account_id}:role/${local.cluster_name_with_suffix}-karpenter" : null
}

output "eks_autoscaler_enabled" {
  description = "Whether EKS Cluster Autoscaler is enabled"
  value       = var.enable_eks_autoscaler
}

output "eks_autoscaler_role_arn" {
  description = "EKS Cluster Autoscaler role ARN (if enabled)"
  value       = var.enable_eks_autoscaler ? "arn:aws:iam::${data.aws_caller_identity.current.account_id}:role/${local.cluster_name_with_suffix}-cluster-autoscaler" : null
}
